import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-[#EEF2F6]`}>
        <Navbar />
        <div className="flex justify-center">
          <div className="w-[108rem] h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
